### ISSUE TITLE
Nepředávat konstanty jako argumenty

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/roboprojekt#101]
Všemi velkými písmeny, např. `WIDTH`, se tradičně pojmenovávají *konstanty* – proměnné, které mají vždycky stejnou hodnotu.
Takové hodnoty není potřeba předávat funkcím jako argumenty. Použijte globální proměnnou (a jestli je nadefinovaná v jiném modulu, naimportujte si ji).

**Comment by befeleme** [comment]
#103
