### ISSUE TITLE
Vytvořit rozhraní hry

### ISSUE THREAD

**Issue by anezkamll** [PyLadiesCZ/roboprojekt#105]
Napsat program, který vykreslí dvě statické části rozhraní - mapu a budoucí interaktivní část, viz obrázek.

**Comment by anezkamll** [comment]
@JureckovaK dodá scan svého rozhraní :)

**Comment by encukou** [comment]
Doporučuju radši napsat *nový* program, který nakreslí nástřel budoucí interaktivní části.

Spojit pak dva programy dohromady je jednodušší než jeden program rozplést – a vede to často k čistším výsledkům.

**Comment by JureckovaK** [comment]
![rozhrani_hry01](https://user-images.githubusercontent.com/38920177/49111395-4e706000-f290-11e8-9120-091b34690600.png)
![rozhrani_hry02](https://user-images.githubusercontent.com/38920177/49111397-4e706000-f290-11e8-817c-5875e5529386.png)

**Comment by vahalova** [comment]
Počty karet ze hry:
U-Turn - 6x
Back up - 5x
Rotate Left - 18x
Rotate Right - 18x
Move 1 - 17x
Move 2 - 12x
Move 3 - 6x

**Comment by vahalova** [comment]
Co se považuje za hotovo? Základní interface máme ne?

**Comment by encukou** [comment]
Jo. Co je potřeba udělat dál? Jaký je tu další krok, a je na něj issue?
