### ISSUE TITLE
Vytvořit třídu rotace

### ISSUE THREAD

**Issue by anezkamll** [PyLadiesCZ/roboprojekt#106]
V backendu ve funkci move nahradí tento if:
```
if direction == 0:
    y += distance
elif direction == 90:
    x += distance
elif direction == 180:
    y -= distance
elif direction == 270:
    x -= distance
```

**Comment by befeleme** [comment]
Zkusim to.

**Comment by encukou** [comment]
Na srazu jsem kreslil tuhle tabulku s informacema, které by se z objektu takové třídy měly dát dostat.

| Směr  | Úhel | Δx | Δy | ⤶ | ⤷ | ↷ | # |
| ------------- | ------------- | -- | -- | -- | -- | -- |  - |
| S  | 0°  | 0 | +1 |  V |  Z | J | 0 |
| V  | 90°  | +1 | 0 |  J | S | Z | 1 |
| J  | 180°  | 0 | -1 | Z  | V | S | 2 |
| Z  | 270°  | -1 | 0 | S | J | V | 3 |

(neručím za správnost)

**Comment by befeleme** [comment]
Čau, 
ubírám se tímto směrem (zatím odděleně od zbytku kódu): Pro tuto třídu jsem si načetla líp typ enum, o němž jsme se bavili před pár týdny. Pořád na tom pracuju (snažím se vstřebat náš UML, aktuální kód a videjko z minulého srazu), ale ocenim příspění, jak to zatím vidíte.
if/elif blok chci vyřešit metodou této třídy, která vypočítá nové x/y. 
Úhly - zde si nejsem jistá, nabízí se opět metoda.  Nebo lepší assign atributů?

```
class Rotation(Enum):
    N = 0
    E = 1
    S = 2
    W = 3

    def __add__(self, other):
        return Rotation((self.value + other.value) % 4)
    def __sub__(self, other):
        return Rotation((self.value - other.value) % 4)

    def turn_right(self):
        return Rotation((self.value + 1) % 4)
    def turn_left(self):
        return Rotation((self.value - 1) % 4)
    def turn_upside_down(self):
        return Rotation((self.value + 2) % 4)
```

**Comment by encukou** [comment]
Jake vidis vyhody & nevyhody tech dvou reseni?

**Comment by befeleme** [comment]
Hlavni problem ted je pro mne uchopit cely obraz. Je to tezsi, nez se zdalo :-). Pokud prepisu tridu "na uhly", muzu s tim pracovat skoro stejne.
```
class Rotation(Enum):
    N = 0
    E = 90
    S = 180
    W = 270

    def __add__(self, other):
        return Rotation(self.value + other.value)
    def __sub__(self, other):
        return Rotation(self.value - other.value)

    def turn_right(self):
        return Rotation((self.value + 90) % 360)
    def turn_left(self):
        return Rotation((self.value + 270) % 360)
    def turn_upside_down(self):
        return Rotation((self.value + 180) % 360)
```

Ale: uz v okamziku rotace vim, jake budou nove koordinaty robota, pokud popojde. Mela bych tedy krome nove rotace v metode vratit rovnou i je? Nebo nevytvaret na ne metodu, ale tvorit objekt rovnou s informaci o novych koordinatech, neco jako:
```
class Rotation(Enum):
    N = (0, (x, y+1))
...
    def __init__(self, rotation_value, coordinates):
        self.rotation_value = rotation_value
        self.coordinates = coordinates
```

(Kod vyse nefunguje, pythonu se nelibi nelibi neprirazene nazvy x, y, ale jde mi spis o myslenku).

K cemu je vycet 0-3, posledni sloupec tabulky, neni mi jasne. Pygletu davame info v uhlech, jak ma vykreslit novy obrazek. V kodu nikde nevidim vyuziti pro tento udaj. 

Ale moment, koordinaty jsou vec robota, nikoli rotace (?). Pak se divam na robota:

```
class Robot:
    def __init__(self, rotation, path, coordinates):
        self.rotation = rotation
        self.path = path
        self.coordinates = coordinates
```

Robot ma rotation a coordinates jako atributy. Muzu vytvorit robota s "rotation" jako objektem jine tridy. Do koordinat zatim nevim, jak pichnout. Nemaji to byt taky objekty tridy "Coordinates"? Jak to zaplest?...
Kreslim si to zde a snazim to rozplest, takze sory za trochu zmatecny popis myslenkoveho pochodu. :)

**Comment by befeleme** [comment]
@encukou, dekuji, ze ses pokusil odpovedet na me pochybnosti. Vysledek dalsiho patrani je v nove verzi PR k revizi.
S cim jsem bojovala: pokud mam atribut .value, ktery ma urcitou hodnotu, ZAROVEN vim, jaky je vektor (nove koordinaty) meho objektu. Nelibilo se mi tedy, ze jednu vec mam ulozenou jako atribut (0, 90, 180, 270) a druhou pridavam v ramci metody get_new_coordinates(). Hledala jsem zpusob, jak mit obe tyto vlastnosti ulozene jako atributy, a zaroven v pripade, ze se meni atribut 1 (value), zmeni se i atribut c.2 (vektor). S tridou, kterou jsem se puvodne snazila vykonstruovat, nebylo to mozne. Pomohlo az prepsani metody __new__(). Nyni objekt, na kterem uplatnim metodu: `Robot.Direction.N.rotate("left")` vrati `Robot.Direction.W.`  

> Jestli je to zbytečné, tak to tam nedávej... Ale máte tak teď v mapách zakódované otáčení posuvných pásů.

Ano, to jsem z prozatimniho uvazovani vynechala, zustava TBD (mozna v ramci dalsi issue)

> Třídu „Coordinates“ nemáte, místo toho používáte dvojice čísel. To neměň, aspoň ne v rámci téhle issue.

Jasne. To by bylo stejne moc velke sousto na raz. :)
