### ISSUE TITLE
Domluvte se na licenci

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/roboprojekt#107]

**Comment by ivet1987** [comment]
Jsem pro Svobodný software, čtyři základní svobody:
0. svoboda používat program za jakýmkoliv účelem
1. svoboda zkoumat a upravovat program (předpokladem je přístup 
ke zdrojovému kódu)
2. svoboda šířit původní verzi programu
3. svoboda šířit upravenou verzi programu

to že to někdo bude chtít upravovat, tak ať, aspoň o to bude zájem a pořád budeme my jako původci :-) My to taky přeci jen "kopírujeme".

**Comment by anezkamll** [comment]
To jo, ale i Free software má svoje licence, třeba právě ty, o kterých mluvil Petr na srazu: https://en.wikipedia.org/wiki/Free_software#Licensing

**Comment by ivet1987** [comment]
Tak to já určitě nepřelouskám anglicky co je co :-D

**Comment by amazonkaarya** [comment]
Hlasuju spíš pro GNU GPL, ale není to pro mě zásadní.

**Comment by anezkamll** [comment]
JJ mám to taky tak, spíš GNU

**Comment by befeleme** [comment]
Za mne taky GNU GPLv3, i když bych chtěla vidět ten velkej korporát, který bere náš cvičný kód, dělá z toho nový tomb raider, a pak vydělává miliony pod nějakým striktním copyrightem bez přístupu ke zdrojákům.
