### ISSUE TITLE
Přidat k políčkům jejich efekty

### ISSUE THREAD

**Issue by JureckovaK** [PyLadiesCZ/roboprojekt#118]

**Comment by JureckovaK** [comment]
Pokračování PR #137 vidím tak, že bude potřeba:
* přidat efekty pohyblivých pásů #149
* napsat testy a otestovat již hotové efekty políček #148 

Bude potřeba taky promyslet, jak budeme realizovat celé herní kolo. Teď mi jde o to, že ve funkci `apply_tile_effects` je nakonci udělané smazání mrtvých robotů a oživení robotů, kteří během herního kola ztratili život, ale ve hře můžou ještě pokračovat. Mám udělat pro tohle samostatnou funkci? Za mě ano. 

Dál spíše k zamyšlení. Petr na srazu zmínil, že při vytváření díry (např. při pohybu mimo hrací plochu: `HoleTile(Direction.N, None, [])`) je potřeba zadat parametry, které jsou v podstatě pro díru zbytečné. To se dá vyřešit nadefinováním metody `__init__` v podtřídě `HoleTile`. Neměla jsem moc čas nad tím přemýšlet, ale pravděpodobně narazíme na problém ve funkci `select_tile`, která pro vytvoření všech políček dostane na vstupu 4 proměnné, které použije pro výběr podtřídy. Tzn. při nadefinování nového initu u díry, tak aby se zadávalo méně parametrů, bude problém v této funkci... Napadá někoho nějaký elegantní způsob, jak to vyřešit?

Pak mám otázku spíš, co se týče angličtiny. Všimla jsem si, že jsem začala požívat proměnné **Start**Tile, **start**coordinates a jinde v kódu je zase **starting**square, get**starting**coordinates. Přiznám se, že jsem to začala zkracovat, protože mi to přišlo dlouhé. Co vám přijde lepší, jak to mám sjednotit?

**Comment by encukou** [comment]
> Petr na srazu zmínil, že při vytváření díry [...] je potřeba zadat [zbytečné] parametry
> [...] pravděpodobně narazíme na problém ve funkci `select_tile`, která pro vytvoření všech políček dostane na vstupu 4 proměnné

Parametry můžou mít výchozí hodnotu: 

```python
def greet(name='world'):
    return 'Hello ' + name + '!'

print(greet())
print(greet('Katko'))
```

> get**starting**coordinates

Jo, sjednocení pomůže. Doporučuju i přidat podtržítka, zvlášť do dlouhých jmen: `get_start_coordinates`

**Comment by JureckovaK** [comment]
> 
> 
> > Petr na srazu zmínil, že při vytváření díry [...] je potřeba zadat [zbytečné] parametry
> > [...] pravděpodobně narazíme na problém ve funkci `select_tile`, která pro vytvoření všech políček dostane na vstupu 4 proměnné
> 
> Parametry můžou mít výchozí hodnotu:
> 
> ```python
> def greet(name='world'):
>     return 'Hello ' + name + '!'
> 
> print(greet())
> print(greet('Katko'))
> ```
Jo takhle! Díky.
> > get**starting**coordinates
> 
> Jo, sjednocení pomůže. Doporučuju i přidat podtržítka, zvlášť do dlouhých jmen: `get_start_coordinates`

Ty podtržítka tam jsou, jenom mi tady pak Markdown napsal kurzívou slova, která jsem nechtěla zvýraznit. Šlo o zvýraznění **start** vs **starting** :)

**Comment by encukou** [comment]
To už je, na zbytek (pásy) jsou samostatné issues.
