### ISSUE TITLE
Vytvořit separátní modul pro funkce, které načítají cesty ke grafice?

### ISSUE THREAD

**Issue by anezkamll** [PyLadiesCZ/roboprojekt#119]
Během práce na načítacím modulu jsme se s @befeleme dostaly k otázce, zda by backendu neprospělo, kdyby se z něj vyčlenilo nejen načítání datového vstupu (u nás nyní JSON soubor vygenerovaný z Tiled), ale i všechno, co jen načítá cesty k obrázkům ve složkách.

**Comment by befeleme** [comment]
Podle me my vlastne nechceme mit v backendu nacitani jakychkoli cest ke grafice - vsechny ty path jsou veci frontendu?...

**Comment by anezkamll** [comment]
Řeší se v rámci https://github.com/PyLadiesCZ/roboprojekt/issues/172
