### ISSUE TITLE
Mapy 4, 5, 6 nefunguji

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#126]
Opravit mapy - nyni jejich nacitani kolabuje: na cestach k souborum, na spatnem tilesetu atd.

**Comment by vahalova** [comment]
To je kvůli té smazané fci `def get_types(data)` ne?

**Comment by JureckovaK** [comment]
Ne, ta je zatím smazaná pouze v PR #122, který ještě není začleněný.

**Comment by amazonkaarya** [comment]
chtěla jsem PR opravit, ale právě dopoledne mi to začalo padat, že se ukázala mapa normálně, ale jak se měli pohnout roboti, tak to spadlo. Neměla jsem čas to řešit, ale teď jdu na PR #122 znovu mrknout

**Comment by vahalova** [comment]
Už snad ok #128
