### ISSUE TITLE
Umírání

### ISSUE THREAD

**Issue by vahalova** [PyLadiesCZ/roboprojekt#127]
Když robot vyjede z mapy, tak spadne hra.

**Comment by encukou** [comment]
Není mi jasné o čem tahle issue je. Jmenuje se "Umírání" – má se řešit že robot nějak umírá? Nebo že spadne hra?
Jak s tím souvisí "Když robot vyjede z mapy, tak spadne hra"?

**Comment by vahalova** [comment]
"Když robot vyjede z mapy, tak spadne hra" robot má umřít a narodit se, zatím třeba na startovacím políčku. To, že kolo nehraje zatím neumíme řešit. 
To stejné, když vjede na díru.
