### ISSUE TITLE
Přidat do skriptu pro export obrázků, aby se ukládaly do jiné složky

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#133]
Nyní skript uloží exportovaná PNGčka do stejné složky, kde jsou SVGčka. My je máme oddělené, a bylo by super, kdyby skript takovou složku:
- pokud neexistuje, vytvořil,
- následně ji naplnil obrázky.

**Comment by ivet1987** [comment]
https://github.com/PyLadiesCZ/roboprojekt/pull/135
