### ISSUE TITLE
Když robot umře, vynechá zbytek kola

### ISSUE THREAD

**Issue by anezkamll** [PyLadiesCZ/roboprojekt#139]
Když robot nějakým způsobem zemře, nasadí se do hry až v následujícím kole, zbytek kola se na ploše neobjevuje

**Comment by anezkamll** [comment]
Aktuálně řešeno přiřazením hodnoty Death v PR #137, kdy robot, který během hry zemře, ale ne definitivně, pouze se na začátku dalšího kola objeví opět na startovním políčku, zmizí do konce stávajícího kola z mapy.

**Comment by encukou** [comment]
Už by to mělo být, ale asi na to nejsou testy?

**Comment by befeleme** [comment]
Teoreticky je tomu tak, ale porad jsme v prvnim kole, nenavysujeme v "prubehu" hry.

**Comment by befeleme** [comment]
To už máme naštěstí hotovo. :)
