### ISSUE TITLE
Robot provede efekt karty

### ISSUE THREAD

**Issue by anezkamll** [PyLadiesCZ/roboprojekt#140]

**Comment by befeleme** [comment]
Chci to zkusit napsat, ale nevím, kde začít, resp. co všechno v rámci této issue se musí pokrýt.

**Comment by encukou** [comment]
Zkus vymyslet menší/konkrétnější podúkoly. Nemusíš vymyslet všechno a začít rovnou psát kód – to udělej, až podúkoly budou dost malé a jasné :)
Pro inspiraci můžeš kouknout na UML diagram.

**Comment by befeleme** [comment]
Koukám, že v diagramu máme více méně podobně rozepsán efekt_karty a efekt_políčka. V kódu původně robotí metoda proved_efekt_policka je momentálně rozepsaná jako funkce, kde políčko provádí akci na robotovi. Není mi jasné, co to dělá a proč takto, ani jak by vypadal kód dle té původní podoby. 

Pokud vezmu na tapetu pouze ty čtyři karetní třídy a přepíšu je do pythonu, vypadá to zatím takto:

```python
class Card:
    def __init__(self, priority, effect):
        self.priority = priority # int - to decide who goes first
        self.effect = effect # CardEffect

class CardEffect:
    def __init__(self, effect_type, rotation, distance):
        self.effect_type = effect_type # CardType
        self.rotation = rotation # Rotation
        self.distance = distance # integer

class CardType(Enum):
    move = 1
    rotate = 2

class Rotation(Enum): # not the passive direction, but movement!
    left = 1
    right = 2
    up_down = 3

karta1 = Card(100, CardEffect(CardType.rotate, Rotation.left, None))
karta2 = Card(100, CardEffect(CardType.move, None, 2))
```

Jenže mi to přijde tak rozkouskované, že vlastně nevidím v tom smysl. Navíc nastavuji zatím dvakrát None, zatímco by asi bylo lepší, aby se nastavoval pouze ten správný parametr (podle vyhodnocení CardType?). 

Je to první zamyšlení nad problémem, jakékoli komentáře uvítám a hodlám to dál skládat.

**Comment by encukou** [comment]
V diagramu nebyla dědičnost. Dala by se využít podobně jako u druhů políček; tam jsme na problém s přebytečnýma argumentama taky narazili.

@vahalova řeší karty v interface, pobavte se, ať je to kompatibilní.

---

K `Rotation`:
* číselné hodnoty doporučuju  zvolit tak, aby se s nimi dobře počítalo v `Direction`
* jednotlivé prvky v Enum se tradičně pojmenovávají jako konstanty:

```python
class Rotation(Enum):
    LEFT = ...
    RIGHT = ...
    BACK = ...
```

**Comment by vahalova** [comment]
Už je čas vyhodit balíček karet do samostatného souboru?
Já tam zatím vytvářím balíček karet, zamíchám a robot dostane 9 karet. 
Seznam dvojic typ a hodnotu karty.
Mrknem na to večer.

**Comment by befeleme** [comment]
@encukou, díky! 
Začíná mi se to projasňovat. Po pár změnách vidím zde začátek k odpíchnutí.
U každé podtřídy jsem definovala vychozí "value" jiným názvem atributu (aby se nám integery nemíchaly dohromady s rotací), ale možná by to ničemu nevadilo?

@vahalova, ano, večer.

```python
class Card:
    def __init__(self, priority, value):
        self.priority = priority # int - to decide who goes first

class MoveCard(Card):
    def __init__(self, priority, value):
        self.distance = value
        super().__init__(priority, value)

class RotateCard(Card):
    def __init__(self, priority, value):
        self.rotation = value
        super().__init__(priority, value)

class Rotation(Enum): # not the passive direction, but movement!
    LEFT = -1
    RIGHT = 1
    UP_DOWN = 2
```
