### ISSUE TITLE
Ve frontendu oddělit načítání obrázků

### ISSUE THREAD

**Issue by anezkamll** [PyLadiesCZ/roboprojekt#144]
Načíst všechny obrázky na začátku a pak na ně už při vytváření spritů jen odkazovat.

**Comment by ivet1987** [comment]
@vahalova jak to tady vypadá? Mám to znovu zkusit nebo na tom děláš?

**Comment by vahalova** [comment]
@ivet1987 Klidně se na to vrhni :-)

**Comment by ivet1987** [comment]
@vahalova po dnesnim srazu už zas nemám čas, třeba časem  🤣
