### ISSUE TITLE
Předělat resize z game do frontendu

### ISSUE THREAD

**Issue by anezkamll** [PyLadiesCZ/roboprojekt#146]

**Comment by befeleme** [comment]
+ prosím, oddělej ten print se spoustou matiky, až bude hotovo :)

**Comment by anezkamll** [comment]
>     * prosím, oddělej ten print se spoustou matiky, až bude hotovo :)
To byl plán ještě pro původní PR, ať se nezačleňuje něco, co tam být nemusí. Toakže hotovo :)
