### ISSUE TITLE
Přidat efekty pohyblivých pásů

### ISSUE THREAD

**Issue by JureckovaK** [PyLadiesCZ/roboprojekt#149]

**Comment by JureckovaK** [comment]
Tak prozatím asi hotovo. Mám tam pár věcí, u kterých vím, že nejsou asi ideálně vyřešeny a potřebovala bych k tomu nějaký komentář 😸

Jak jsem psala v komentáři PR #170 , tak efekty pásů jsem řešila úplně jinak než zbylé efekty políček. Problém je v tom, že při řešení pásů nás nezajímá jenom jedno políčko, ale i roboti na všech ostatních pásech, protože podle pravidel se všichni pohybují současně. No a tak mám hlavní část řešení ve funkci v backendu, která se jmenuje `move_belts`, která si volá pomocné funkce jak z backendu, tak z utilu. No a nevím, jestli to není už moc velký guláš 😆 Mně osobně to dává smysl, ale určitě by se to dalo napsat líp, že?

Hlavní myšlenka je taková, že si zjistím, kteří roboti stojí na pásech, na jakých konrétních pásech stojí a na kterých souřadnicích. Postupně potom hýbu roboty podle pásů, ale jen v případě, že na dalších souřadnicích není další robot na páse, který by se měl pohnout první. V takovém případě robot počká dokud se robot v cestě nepohne.

Pokud bychom to moje řešení zachovali tak mám pár dotazů.
Jedna z těch pomocných funkcí slouží ke zjištění všech robotů, kteří jsou na pásech a měli by se pohnout: funkce `get_robots_on_belts`. Potřebuju si uložit tři údaje: robota, jeho pás a jeho souřadnice. Momentálně mám tyto údaje uložené ve slovníku: klíče jsou souřadnice a hodnoty jsou tuple robota a políčka pásu. Vybrala jsem správný datový typ? Ptám se, protože v hlavní funkci postupně jednotlivé záznamy ze slovníku mažu, potom co se robot pohne na páse. 

S tím mazáním záznamů slovníku je spojené i to, že jak procházím cyklem slovník, tak pokaždé, když smažu záznam, musím cyklus ukončit, protože se slovník změnil. To bohužel vede v tomu, že nad cyklem procházející slovník je while cyklus. No a to je ten guláš, o kterém mluvím...

Mám někdo nápad na elegantnější řešení?

**Comment by encukou** [comment]
Ty jo, koukám že pohyb robotů je nakonec složitější než jsem čekal :)
Pojďme z toho udělat ukázku toho, jak se dělá *návrh algoritmu*.

Zkus se vrátit na začátek a popsat algoritmus (= postup) napřed česky, než ho „přeložíš“ do Pythonu. Zbaví tě to starosti o detaily, které od samotného postupu odvádí pozornost.
Doporučuju strukturovaně zapsat, jak pohnout robotama. Tvoji „hlavní myšlenku“ bych přepsal jako:

* zjistím, kteří roboti stojí na pásech, na jakých konrétních pásech stojí a na kterých souřadnicích. Výsledek dám do slovníku (robot → (souřadnice, políčko pásu)).
* Postupně potom pro každého robota:
  * V případě, že na dalších souřadnicích je další robot na páse (který by se měl pohnout první), robot zatím počká.
  * Jinak se robot pohne.

Přepsal jsem to z tvého komentáře, ne z kódu, takže to takhle asi nebude fungovat – proč?
Technická omezení (např. při mazání záznamů slovníku) teď nech být.
Dej to třeba do Google dokumentu, ať se to dá připomínkovat.

K návrhu algoritmů (instrukcí pro „blbé“ počítače) se doporučuju kouknout na tohle video. Je trochu přehnané, ale zato vtipné: https://www.youtube.com/watch?v=cDA3_5982h8
