### ISSUE TITLE
Naučit roboty střílet laserem

### ISSUE THREAD

**Issue by JureckovaK** [PyLadiesCZ/roboprojekt#161]
Přidat robotí metodu na střílení laserem. Laser robota neprochází zdí a zasáhne pouze prvního robota v cestě. Laser putuje přes hrací plochu dokud nenarazí na zeď nebo robota. Robot zasažený laserem získá jedno zranění. Roboti s PowerDown nestřílí, ale můžou být zasaženi.

**Comment by encukou** [comment]
> dokud nenarazí na zeď nebo robota
Ještě je

**Comment by encukou** [comment]
(Omlouvám se za nechtěné zavření)

**Comment by befeleme** [comment]
Ještě není vyřešeno: 
> Roboti s PowerDown nestřílí, ale můžou být zasaženi.

**Comment by befeleme** [comment]
Nyni cela issue by mela byt pokryta.
