### ISSUE TITLE
Postupne navysovat herni kola

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#164]
Zatim porad hrajeme kolo c. 1 ;) 
Chceme mit 5 kol, behem nichz se zahraje karta na ruce a postupne provedou efekty policek.

Neni to high priority ted hned (nejprve musime doresit efekty policek a integrovat karty).

**Comment by encukou** [comment]
Čím je tohle blokované?
Chcete to ještě? Není to hotové?
