### ISSUE TITLE
Spousta malých vylepšení a zjednodušení

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/roboprojekt#172]
Úkoly vhodné pro to abyste se seznámily s kódem. Jestli kódu už rozumíš, nedělej je a omez se na review.

* [x] V `backend.py` je `get_tile_count`, a mezi `get_start_state` a `State.__init__` se `tile_count` přejmenuje na `sizes`. Použijte jen jeden termín.
* [x] To co teď je `State.game_round` se podle pravidel řekne `register`.
* [x] `Robot.walk` se zápornou `distance` a nastaveným `direction` asi nefunguje.
* [x] v `Robot.walk` není `robot_in_the_way` robot, ale číslo. Proč?
* [x] v `Robot.walk` by bylo dobré dát `else` k `if distance < 0`, aby bylo vidět že se ten `for` neprovede.
* [x] v `Robot.walk` je v komentáři `new coordinates`, ale proměnná se jmenuje `next_coordinates`. Prosím sjednotit.
* [x] v `Robot.walk`: pokud je cizí robot v cestě i po tom, so jsme jím pohli, boužijte `break` jako by v cestě byla zeď. `self.coordinates = next_coordinates` atd. pak bude v kódu jen jednou.
* [x] `Robot.walk` a `Robot.move` jsou skoro stejné. Zbavte se duplikace.
* [x] Místo `Robot.apply_card_effect(card)` by stačilo `Card.apply(robot)` (v každé podtřídě Card jiné).
* [x] Místo `Robot.path` a `Robot.path_front` roboty pojmenujte (`Robot.name`).
* [x] Souřadnice neaktivního robota nedávají nikdy smysl jako čísla (x, y); kód který je používá je špatně. Místo `(-1, -1)` použijte `None`.
* [x] Popřemýšlejte nad metodou `State.get_active_robots`
* [x] V `apply_tile_effects` je `if state.register== 5:`, což se mi vůbec nelíbí. `set_robots_for_new_turn` by se měla volat zvlášť.
* [x] Udělejte `tile.py`, je toho tam o políčkách spousta.
* [x] Zbavte se `Tile.path`.
* [x] Políčka (`Tile`) by měla jako `properties` dostat civilizovaný slovník jako `{'crossroads': True, 'direction': 90, 'count': 2}, a neměla by ignorovat jména vlastností.
 * [x] `GearTile.transform_direction` by mohla být funkce.
* [x] Jestli chcete, zjednodušte `LaserTile.shoot_robot`.
* [x] `util.select_tile` nevybírá, ale i vytváří políčko.

---

* [x] V `get_start_tile` se dívat na vlastnosti políčka, ne na obrázek
* [x] `get_robot_paths` by mělo být ve frontendu. Udělejte ale soubor, ve kterém budou jména robotů, co jsou k dispozici (na výběr na začátku hry). Jména berte z něj.
* [x] `get_robots_to_start` vytváří Roboty a vrátí jejich seznam. Měla by se podle toho jmenovat.
* [x] `check_wall` vrací True, když tam zeď *není*. Změňte buď jméno nebo návratovou hodnotu.
* [x] `if move_from:` a `if move_to:` v  `check_wall`  jsou zbytečné – ty proměnné jsou v daný moment vždycky `True`.
* [x] `frontend.init_window` okno vytváří, ne jen inicializuje. Pojmenujte ji podle toho. (A v interface taky)
* [x] `frontend.draw_board` nekreslí `board`, ale stav.

* [x] V interface sjednoťte `table` a `deal_cards`
* [x] `interface.get_deal_cards` se dá napsat bez cyklu

**Comment by befeleme** [comment]
>     * `Robot.walk` se zápornou `distance` a nastaveným `direction` asi nefunguje.

`asi`? Četla jsem teď o tom odstavec v PR na další blog post a zkouším přijít na to, v čem jste spatřili problém. Otestovala jsem to v rámci mapy č. 3 ve všech směrech (PR #176) + dodatečně na mapě, kde couvající robot posune jiného robota dozadu - podle mě vše se odehrává OK: posunutí roboti mají správný směr a jdou o správný počet míst dál.

**Comment by encukou** [comment]
Tím nastaveným `direction` jsem myslel něco jako:
```
robot = Robot(Direction.N, None, None, (5, 5))
robot.walk(-1, state, direction=Direction.W)
```

**Comment by befeleme** [comment]
Premýšlím, jestli (a kdy) se vůbec do takového kódu můžeme dostat. Podle mě to teď není možné. Walk je metoda, kterou robot provede pouze jako efekt karty. Po ceste může posunout ostatní roboty. Kód, který zajišťuje posunutí dalšího robota v cestě (což je jediný případ, kdy `self.direction` nemusí být rovno `direction`), už nepracuje se zápornou hodnotou. 
Ráda se o tom pobavím v úterý. 

```python
# Move robot in the way.
if robot_in_the_way is not None:
    state.robots[robot_in_the_way].walk(1, state, direction)
    # Check that robot moved.
    if state.robots[robot_in_the_way].coordinates != next_coordinates:
           # Robot walks to new coordinates.
           self.coordinates = next_coordinates
           # Check hole on new coordinates.
           self.check_hole(state)
```

**Comment by encukou** [comment]
Jestli ta metoda vyžaduje jenom určité kombinace argumentů, aby dělala to co má, specifikujte to v dokumentaci.

Všechno, co bych o této metodě měl vědět, když ji budu chtít zavolat, je:
```python
    def walk(self, distance, state, direction=None):
        """
        Move a robot to new coordinates based on his direction.
        Optional argument:
            direction - Default value is set to robot's direction.

        When robot walks, he can move other robots in the way.
        """
```

Jestli je tam nějaká výjimka jen kvůli tomu, že se tahle metoda v aktuálním kódu nějakým způsobem nevolá, musí každý, kdo tu metodu chce použít (na něco, co ještě program neumí), znát celý aktuální program a jeho návrh.
Udržovatelný software se zkládá z částí, které se dají použít nezávisle na sobě.

**Comment by JureckovaK** [comment]
Napadá mě jeden příklad, kdy bude potřeba stávající kód upravit. Když jsem psala efekty políček a řešila jsem, jestli umí pushery posouvat víc robotů v řadě nebo ne. Na internetu jsem se dočetla, že většinou to hrají tak, že pushery mají dost síly, aby posouvali víc robotů za sebou. My to hrajeme tak, že pusher takovou sílu nemá. V momentě, kdy to bude chtít změnit, použiju u pusherů místo metody `move` metodu `walk`. 

U pusheru vypadá volání takto:
`robot.move(self.direction.get_new_direction(Rotation.U_TURN), 1, state)`
A já bych chtěla použít toto:
`robot.walk(-1, state, self.direction)`
Zadáním argumentu `distance` jako -1, se vyhnu otáčení směru pusheru o 180°. A vizuálně kód vypadá lépe než:
`robot.walk(1, state, self.direction.get_new_direction(Rotation.U_TURN))`
Hlavní rozdíl mezi obě zápisy je v tom, že první případ nebude fungovat kdykoliv se bude lišit směr pusheru od směru robota.

Dává to smysl?

**Comment by ivet1987** [comment]
https://github.com/PyLadiesCZ/roboprojekt/pull/177

**Comment by ivet1987** [comment]
https://github.com/PyLadiesCZ/roboprojekt/pull/218

**Comment by ivet1987** [comment]
https://github.com/PyLadiesCZ/roboprojekt/pull/227
