### ISSUE TITLE
Nechceme aby hráči vypadávali ze hry

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/roboprojekt#175]
Asi největší nešvar první edice deskovky Robo Rally je, že hráči můžou vypadnout ze hry.
Já to řeším tak, že místo toho se robotovi, který přijde o všechny životy, dá *permanentní* zranění (vždy, když umře). Hra je pak mnohem lepší :)

**Comment by vahalova** [comment]
Asi nechápu, 3x umře a dostane zranění místo vypadnutí nebo u každého umření?

**Comment by anezkamll** [comment]
Já jsem to pochopila tak, že 3x umře (a odečítají se mu životy) a až se u životů dostane na nulu, pokaždé, kdy by měl znovu umřít, protože už nemá život, který by se mu odečetl, dostane místo toho permanentní zranění.

**Comment by vahalova** [comment]
No já jsem zmatená, protože jsem to tento týden hráli a já umřela 1x a Petr říkal, že si mám nechat jedno zranění...

**Comment by encukou** [comment]
To je jiné pravidlo, které jsem si navíc pamatoval špatně – mají to být 2 zranění. Z pravidel:
> Robots reentering the race receive 2 Damage tokens (plus any Damage tokens taken while powered down).

Ale ty nejsou permanentní, dají se opravit.

**Comment by vahalova** [comment]
OK. Tak to by pak chtělo vizuálně odlišit, co je normální zranění a co permanentní.

**Comment by ivet1987** [comment]
https://github.com/PyLadiesCZ/roboprojekt/pull/337
