### ISSUE TITLE
Roboti by se meli inicializovat ve smeru startovaciho policka

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#178]
Nyni se nam roboti inicializuji vzdy "na sever", nepracujeme se smerem startovaciho policka. 
Nove by se meli inicializovat ve smeru startovaciho policka, na nemz stoji.

**Comment by encukou** [comment]
Tuhle změnu bude asi jednodušší udělat společně s https://github.com/PyLadiesCZ/roboprojekt/issues/179 (Poradi robotu v seznamu robotu)
