### ISSUE TITLE
Poradi robotu v seznamu robotu

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#179]
Kdyz se roboti inicializuji na startovacich polickach, neda se jiste urcit, ktery robot je kde v poradi. Bylo by lepsi, kdyby se spolehlive inicializovali v poradi stejnem jako jsou cisla startovacich policek.
Ted me jeste napada, ze behem hry se roboti mazou ze seznamu robotu, kdyz umrou, cim by se poradi menilo. Toto chovani nejspis zmenime, viz #175.

**Comment by encukou** [comment]
Tuhle změnu bude asi jednodušší udělat společně s https://github.com/PyLadiesCZ/roboprojekt/issues/178 (Roboti by se meli inicializovat ve smeru startovaciho policka)
