### ISSUE TITLE
Metoda robota walk nefunguje správně

### ISSUE THREAD

**Issue by JureckovaK** [PyLadiesCZ/roboprojekt#185]
Když spustím stávající kód, tak v momentě, kdy robot stoupne na díru, spadne hra. Podle chybové hlášky je problém v robotí metodě `walk`. Narazila jsem na to dnes při spuštění mapy `test_effects.json`.

**Comment by befeleme** [comment]
Problém je způsoben změnou koordinát neaktivních robotů (-1, -1) na None.

**Comment by befeleme** [comment]
@ivet1987, chceš se na to podívat? Myslím si, že tento debugging bude zajímavý. Skrz chybové výpisy přijdeš na to, kde je třeba ošetřit podmínky pro výskyt  `None`.

**Comment by ivet1987** [comment]
Jestli to spěchá tak tento týden bohužel nebudu mít čas :(

**Comment by ivet1987** [comment]
@JureckovaK @befeleme můžete mě kopnout jak postupovat? Chybové hlášky vidím, ale nevím co vlastně napsat za podmínky, pokud ty coordinates jsou None, tak co?

**Comment by befeleme** [comment]
@ivet1987, neslibuju, ze se dostanu k pocitaci dalsi dva dny :/ 
ale: problem je ve funkci 
```python 
def get_next_coordinates(coordinates, direction):
    """
    Get next coordinates in the given direction from current coordinates.
    """
    (x, y) = coordinates
    (new_x, new_y) = direction.coor_delta
    x = x + new_x
    y = y + new_y
    return (x, y)
```
Tato funkce bere koordinaty robota, rozdeli je na x, y a vypocita nove na zaklade smeru danemu robotovi. Kdyz jsou koordinaty `None`, mame problem, nejdou rozdelit, ani nejde k nim nic pricitat. 
Bud se tedy zmeni tato funkce, ze nebude nic pocitat, pokud koordinaty jsou `None`, nebo tam, kde se tato funkce vola, nebudeme do seznamu zahrnovat neaktivni roboty. Nevim, ktera cesta je lepsi, treba ti napovi Katka, pripadne se o tom pobavte v utery na srazu.

**Comment by JureckovaK** [comment]
No moje první myšlenka byla taková, že když robot stoupne na díru, tak vlastně už nechci, aby se dál hýbal tzn. aby se pohyb robota ukončil. V takovém případě by už nebylo nutné řešit další funkce/metody, které se využívají při pohybu a předpokládají určitý typ vstupu. Podobně jsem to řešila i při aplikaci efektů políček, kdy se v momentě umření robota ukončí provádění konkrétního efektu políčka na konkrétním robotě.

**Comment by ivet1987** [comment]
tak hra už nepadá ale neprochází testy a já nevím jak je spravit :(
https://github.com/PyLadiesCZ/roboprojekt/pull/194

**Comment by ivet1987** [comment]
předpokládám protože ty testy volají metodu walk, ve které se smazalo check_hole(nyní fall_into_hole) a ta ubrala robotu život že? Já jen jestli to dobře chápu. Ale nevím jak to opravit.

**Comment by ivet1987** [comment]
https://github.com/PyLadiesCZ/roboprojekt/pull/194

**Comment by ivet1987** [comment]
https://github.com/PyLadiesCZ/roboprojekt/pull/197

**Comment by befeleme** [comment]
Právě jsem roboty vyhodila z testovací mapy (= spadli do díry), a dostala jsem tento výpis:

```python
  File "game.py", line 48, in move_once
    robot.walk(3, state)
  File "/home/karo/dev/roboprojekt/backend.py", line 61, in walk
    if not check_the_absence_of_a_wall(self.coordinates, direction, state):
  File "/home/karo/dev/roboprojekt/backend.py", line 388, in check_the_absence_of_a_wall
    next_coordinates = get_next_coordinates(coordinates, direction)
  File "/home/karo/dev/roboprojekt/util.py", line 70, in get_next_coordinates
    (x, y) = coordinates
TypeError: 'NoneType' object is not iterable
```

**Comment by ivet1987** [comment]
https://github.com/PyLadiesCZ/roboprojekt/pull/202
