### ISSUE TITLE
Udělat server

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/roboprojekt#191]

**Comment by encukou** [comment]
Server:
* [ ] Informuje připojené programy o stavu hry
* [ ] Ptá se hráčů na další tah
* [ ] Dostává informace o dalším tahu
* [ ] Spravuje stav hry

1. Navrhněte formát (JSON) pro každou ze zpráv, které server posílá nebo přijímá.
2. A pak napište server, co to bude posílat/přijímat.

**Comment by ivet1987** [comment]
https://github.com/PyLadiesCZ/roboprojekt/pull/223

**Comment by ivet1987** [comment]
https://github.com/PyLadiesCZ/roboprojekt/pull/240

**Comment by befeleme** [comment]
[ ] - udělat design dokument s popisem fungovani servru

**Comment by ivet1987** [comment]
https://github.com/PyLadiesCZ/roboprojekt/pull/247

**Comment by ivet1987** [comment]
https://github.com/PyLadiesCZ/roboprojekt/pull/249

**Comment by befeleme** [comment]
Behem procitani kodu a dokumentace bojovala jsem s temi otazkami: 
- Jak server vi, kdo se k nemu pripojil (receiver - interface)?
- Jak server rozlisuje, komu co posila (stav hry - receiveru, kart - interface'u)?
- Jak server dava najevo, jaky druh informaci posila (rekne to posilanym JSONem?)
- Dela to vsechno server jako jednu dlohou proceduru `websocket`, nebo (a jak) mu jednotlive tasky rozdelit?

Vysledkem je zbastleny kod, ktery jsem poslala jako draft PR. Cil je hlavne mit podklad, na nemz muzeme diskutovat v utery. #259

**Comment by ivet1987** [comment]
https://github.com/PyLadiesCZ/roboprojekt/pull/282

**Comment by befeleme** [comment]
Predpokladam, ze na poslednim bodu zatim nikdo nepracuje, tak ho beru pod sebe.
