### ISSUE TITLE
Napsat testy

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/roboprojekt#20]

**Comment by zstankova** [comment]
První test je v #27

**Comment by befeleme** [comment]
```
def get_tiles(data):
    """
    Return the complete list of tiles.
    data: a dict created from decoded Tiled 1.2 JSON file
    Get the list of all tiles from the list "data" within the list "layers". 
    """
    rotation_dict = {0:0, 10:90, 12:180, 6:270}
    tilelist = {}
    for layer in data['layers']:
        tilelist_layer = []
        for data in layer['data']:
            real_tile = data & 0xFFFFFF
            rotation_index = data >> (4*7)
            rotation = rotation_dict[rotation_index]
            tile = Tile(real_tile, rotation)
            tilelist_layer.append(tile)
        tilelist[layer['id']] = tilelist_layer
    return tilelist
```

Divam se na tuto funkci a zjistuju, ze nevim, jak ji testovat. 
Zaprve - dela strasne moc veci a pro ty testy mam chut ji rozkouskovat minimalne jeste na:
- get_decimal_id_from_hex(int) -> int (v desitkove soustave)
- get_decimal_rotation_from_hex(int) -> int (v desitkove soustave)

pak se zde vytvari objekty tridy Tile, ktere se pridaji do seznamu dane vrstvy, a ty pak do slovniku. Slovnik ma nasledne podobu, u ktere taky nevim, jak nadefinovat test, priklad nize: 

`{1: [<__main__.Tile object at 0x7ff32797f5c0>, <__main__.Tile object at 0x7ff32797f5f8>, <__main__.Tile object at 0x7ff32797f630>, <__main__.Tile object at 0x7ff32797f668>, <__main__.Tile object at 0x7ff32797f6a0>, <__main__.Tile object at 0x7ff32797f6d8>, <__main__.Tile object at 0x7ff32797f710>]}`
Any ideas? @encukou, @zstankova ?

**Comment by befeleme** [comment]
#104
