### ISSUE TITLE
Vytvořit pro třídu Robot metodu, která roboty popíše ve formě slovníku

### ISSUE THREAD

**Issue by anezkamll** [PyLadiesCZ/roboprojekt#213]
Pro účely komunikace mezi klientem a serverem je třeba mít roboty popsané v takové formě, s tím server dokázal pracovat, když předává stav hry. 
Souvisí s https://github.com/PyLadiesCZ/roboprojekt/issues/191

**Comment by ivet1987** [comment]
To už částečně provizorně je v https://github.com/PyLadiesCZ/roboprojekt/pull/208, takže udělám a pošlu PR pouze s tímto :-)

**Comment by ivet1987** [comment]
https://github.com/PyLadiesCZ/roboprojekt/pull/214

**Comment by ivet1987** [comment]
HOTOVO
