### ISSUE TITLE
Napsat třídy podle UML diagramu

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/roboprojekt#22]

**Comment by anezkamll** [comment]
![uml1](https://user-images.githubusercontent.com/6068291/48152239-97517c00-e2c3-11e8-96cc-7ecc8afb9000.jpg)

**Comment by encukou** [comment]
Konvence na pojmenovávání proměnných/tříd s více slovy:
* `normalni_promenna`, `jmeno_funkce`, `jmeno_metody`, `parameter_funkce`, `nejaky_modul`
* `NEJAKA_KONSTANTA`
* `NejlepsiTrida`

**Comment by encukou** [comment]
Třídy dělejte postupně, jak budou potřeba – ale nezapomeňte se na ten diagram kouknout, když nějakou budete psát.
