### ISSUE TITLE
Roboti s Power Down

### ISSUE THREAD

**Issue by JureckovaK** [PyLadiesCZ/roboprojekt#232]
Vyřešit, jak se tito roboti ve hře chovají.

Robot s Power Down:
 - na začátku kola vynuluje všechna zranění
 - robot nedostane žádné karty a ani žádné karty hrát nebude
 - efekty políček na něj stále platí
 - ostatní roboti můžou robota s Power Down posouvat
 - může být zasažen laser robota, tedy může i po vynulování získat během herního kola nová zranění

Když hráč zahlásí Power Down, projeví až v následujícím kole. Pokud robot během zbytku kola umře, může se na začátku nového kola rozhodnout, jestli pořád chce Power Down nebo ne. 

Během rozdávání karet se hráč s Power Down může rozhodnout, jestli chce Power Down ponechat (třeba kvůli novým zraněním, které během předchozího kola s Power Down získal) nebo ne.

**Comment by encukou** [comment]
A ještě myslím že:
* Robot s Power Down nestřílí

**Comment by befeleme** [comment]
Nejradši bych nám život nekomplikovala a řešila tyto otázky cestou minimální funkčnosti:

> Během rozdávání karet se hráč s Power Down může rozhodnout, jestli chce Power Down ponechat (třeba kvůli novým zraněním, které během předchozího kola s Power Down získal) nebo ne.

Vytváříme vždy nový stav inferface po skončeném kole. Nevidím problém v tom, aby hráč, který byl předchozí kolo zamražen, opět stiskl klávesu/ tlačítko na Power Down a aktivoval ho ještě jednou. Pokud ale vybere karty a výběr potvrdí, PD se na něho toto kolo vztahovat nebude. 

> Když hráč zahlásí Power Down, projeví až v následujícím kole. Pokud robot během zbytku kola umře, může se na začátku nového kola rozhodnout, jestli pořád chce Power Down nebo ne.

Hra tím, s jakou rychlosti přeskakuje registry, neumožňuje nám dělat rozhodnutí dynamicky během provádění registrů. To se jednou změní, ale vlastně nevidím tak zásadní, abychom podporovaly tento use case. Můj návrh na řešení je tedy:
- Power Down můžeš stisknout po rozdání karet do momentu potvrzení výběru / doběhnutí timeru a platí na stávající kolo. Potvrzením výběru Power Down (klávesa k) dojde k vynulování zránění a karet na ruce. Ostatní hráči by měli vědět, že daný robot nehraje (grafické vykreslení). 
- v novém kole Power Down zmizí a pokud chceš s ním pokračovat, musíš opět zmáčknout příslušnou klávesu (to platí i na případ, že je robot vypnut a během kola umře)

Pak během PD platí:

- efekty políček na něj stále platí
- ostatní roboti můžou robota s Power Down posouvat
- může být zasažen laser robota, tedy může i po vynulování získat během herního kola nová zranění
- Robot s Power Down nestřílí

Co si o tom myslíte?

**Comment by anezkamll** [comment]
> Nejradši bych nám život nekomplikovala a řešila tyto otázky cestou minimální funkčnosti
S tímhle souhlasím zcela, je to i v duchu toho přivést hru do skutečně hratelné podoby. Nad jednotlivými kroky se ještě musím zamyslet :) Ale na první přečtení to zní dobře, jak říkáš, v současné chvíli to potřebujeme ohnout podle toho, jak hra probíhá teď (provádění akce registrů).
