### ISSUE TITLE
Vrácení neaktivních robotů

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#235]
Všichni se zatím vrátí na své startovací koordináty a otočení na sever.
Mohli by být schopní se otočit (zvolit směr), a v případě, že víc robotů inicializuje se na stejné políčko, postaví se vedle sebe, místo aby si sedli na hlavu.

**Comment by ivet1987** [comment]
@befeleme kdybys chtěla udělat, zatím se odhlasuju. 😁
