### ISSUE TITLE
Úkoly pro client_interface

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/roboprojekt#251]
* [x] z `interface_frontend` odstranit globální proměnné (`interface_state`, `window`, `program`) a volání funkcí (`create_window`, `pyglet.app.run`)
  * [x] oddělat dekorátory `@window.…`
  * [x] `interface_state`, `window` dávat jako argumenty, kde jsou potřeba
* [x] z `my_program` udělat seznam čísel (indexů do `dealt_cards`)
* [x] udělat `on_draw` a `on_text` v `client_interface`
* [x] v `on_text` posílat seznam karet serveru
* [x] zařídit aby se klient neodpojoval

**Comment by ivet1987** [comment]
https://github.com/PyLadiesCZ/roboprojekt/pull/249
