### ISSUE TITLE
Volání funkcí v interface.py

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#255]
https://github.com/PyLadiesCZ/roboprojekt/blob/257eaf49820077790825aa344c6733deb9973919/interface.py#L116

https://github.com/PyLadiesCZ/roboprojekt/blob/257eaf49820077790825aa344c6733deb9973919/interface.py#L128

V budoucnu to tam nejspíš nechceme.

**Comment by encukou** [comment]
Ani `get_interface_state` nechcete :)

**Comment by befeleme** [comment]
Ona se tam teď nevolá. Nebo myslíš i tu definici?
