### ISSUE TITLE
Rozšířit funkčnost klientů

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#266]
Interface
- [x] posílá servru zprávu s daty (atributy svého stavu): vybrané karty, power down, indicator - vymyslet pro to JSON formáty
- [x] zpracuje obdržená data: karty a robota (vykreslí)
- [x] umí vytvořit prázdný stav - bez karet
- [x] umí vytvořit prázdný stav - bez robota (odstranit testovací data z interface.py / interface_frontend.py)
- [x] umí vykreslit roboty ostatních hračů - avatary dole

**Comment by ivet1987** [comment]
úkol první: https://github.com/PyLadiesCZ/roboprojekt/pull/269

**Comment by ivet1987** [comment]
zatím hotov první bod, který další budu dělat nevím, tak kdyžtak písněte, když se na něco vrhnete, moc času už do konce týdne mít nebudu.

**Comment by ivet1987** [comment]
https://github.com/PyLadiesCZ/roboprojekt/pull/281

**Comment by ivet1987** [comment]
Musí se upravit 
```python
elif "robot_data" in message:
    robot = Robot.from_dict(message)
    self.state.robot = robot
```
Robota si bude vždy načítat ze zprávy state.as.dict, kde je několik robotů, tedy několik "robot_data"
