### ISSUE TITLE
Rozšířit stav hry

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#267]
- Balíček karet a balíček odhozených karet přidat do stavu hry. Balíčky jsou ale tajné, neposílají se se stavem hry klientům.

**Comment by ivet1987** [comment]
Dotaz - vytváření balíčku a všechen kód kolem toho bude v backendu po třídou State? 
Takže v initu bude `def __init__(self, board, robots, card_pack, del_cards)?

**Comment by encukou** [comment]
Buď tak, nebo jen `def __init__(self, board, robots)`, s tím že se balíček namíchá automaticky (a dá se potom změnit).
Co bude lepší?

**Comment by ivet1987** [comment]
nějak nevím jak myslíš automaticky namíchat balíček , netuším co je lepší.

**Comment by encukou** [comment]
> nějak nevím jak myslíš automaticky namíchat balíček

Vytvoří si balíček karet, co mají být ve hře, a zamíchá ho.

> netuším co je lepší

Jak to zjistíš?

**Comment by ivet1987** [comment]
Nevím. Asi bych to dala zvlášť. A musím si pustit záznam, nevím teď proč potřebujeme odhazovací balíček.

**Comment by encukou** [comment]
> Nevím. Asi bych to dala zvlášť.

Pokud nevíš, můžeš to zkusit začít dělat tak i tak (ve dvou větvích/pull requestech), dokud to nezjistíš. Je to víc práce, ale třeba se něco naučíš :)

**Comment by ivet1987** [comment]
Zatím to nebudu asi dělat, jestli chcete @befeleme @JureckovaK volné :-D

**Comment by befeleme** [comment]
Tak jo, zkusím si s tím pohrát.

**Comment by befeleme** [comment]
zbývá: 
- [ ] zpracovat balíček odhozených karet
- [ ] přidat číslo hraného kola

**Comment by befeleme** [comment]
Karty se přenáší do odhozeného balíčku:
- poté, což si hráč vybere svých 5 karet a potvrdí výběr NEBO dojde mu čas a server mu vybere 5 karet 
      -> 4 zbývající karty putují do balíčku
- po každém registru zahraná karta se ověří, zda je v blokované pozici
      -> pokud není, putuje do balíčku
      -> pokud je, nebude přidaná do balíčku

Z toho mi vyplývá, že zamčené pozice karet budeme řešit v interface jako další atribut stavu rozhraní. Implementaci ještě nemáme, ale místo na ní můžeme už připravit.

Jsou ještě případy, že karta bude použitá jinde/ jinak?

**Comment by ivet1987** [comment]
Co prosim te znamena blokovana pozice karty? To je kdy?

**Comment by befeleme** [comment]
To je to v #284 - karty, které se robotovi blokují, nebudou přidané do balíčku.

**Comment by ivet1987** [comment]
"Pokud robot má víc než 4 zranění, zablokují se mu příslušné karty na ruce"
Stale ti nechápu. Jake příslušné karty na ruce se zablokují? Jakoze kdyz ma 4 zraneni tak se mu blokne 1 a vybírá jen 4 nebo to je to permanentní zraneni ze dostane méně dealt card?

**Comment by befeleme** [comment]
Když otevřeš interface, jsou tam čáry vedoucí od zranění do karet a podpis "lock". Když robot dostane 5. zranění, nemůže vybírat 5, ale jen 4 karty. S každým další zraněním o jednu méně.

**Comment by ivet1987** [comment]
Hele čáry :-D Těch jsem si nikdy nevšimla :-D

**Comment by ivet1987** [comment]
myslím že by pomohlo vyjádření @encukou jak to nejlépe řešit, zda jako další atribut, já si s tím vůbec nevím rady jak to udělat.
Jo ahááá jak to pořád čtu dokola, až teď mi došlo že se mluví o zamčení POZICE karty, ne zamčení některých karet, tak už to chápu ale stejně nevím jak to řešit.
