### ISSUE TITLE
Přidat dokumentační řetězce

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/roboprojekt#28]
Čím víc lidí (nebo kousků kódu) používá nějakou funkci, tím je k ní důležitější napsat *dokumentaci* – popis toho, co ta funkce dělá. Člověk si může číst samotný kód, ale tam není všechno.

Dobrá jména funkcí a argumentů už jsou dokumentace sama o sobě. Třeba:
```python
def add(a, b):
    return a + b
```
… je OK pro funkci, kterou používám někde níž v tom samém souboru. Když si ale jen přečtu kód, není jasné např. jestli je tuhle funkci dobré zavolat na řetězce, `add("Hello, ", "world!")`.
```python
def add(a, b):
    """
    Add two numbers

    `a` and `b` should be numbers (int or float).
    Returns the sum.
    """
    return a + b
```
Velké projekty, kde je potřeba aby se s kódem mohl každý co nejrychleji seznámit a korektně ho měnit, to berou fakt vážně, a dokumentace je často delší než samotný kód – viz třeba [tenhle kód z Javy](http://www.docjar.net/html/api/java/util/Collections.java.html).
Používají se i nástroje, které ověří že *každá* funkce a *každý* argument jsou zdokumentované. To už je docela extrém (u mladšího projektu se pak může stát, že se změní kód ale neaktualizuje dokumentace, a dokumentace co neodpovídá kódu je horší než žádná dokumentace). Ale je dobré se u každého argumentu aspoň *zamyslet*, jestli o něm jméno říká všechno co je potřeba.

Do dokumentačních řetězců (viz [materiály](https://naucse.python.cz/course/pyladies/beginners/def/), nebo do vyhledávače dej `docstring`) je dobré psát *co* funkce dělá, jaké bere argumenty, co vrací. U složitějších struktur (seznam dvojic slovníků souřadnic) je dobré uvést příklad, aby si to člověk líp uvědomil
Do normálních komentářů je dobré psát *jak* se to dělá, jak funkce postupuje – věci, které nezajímají toho, kdo pak bude funkci volat.
Například:
```python
def get_coordinates(data):
    """
    Get a list of tile coordinates for a map

    `data` is a dict loaded from a Tiled 1.2 JSON file.
    Returns a list of all tile coordinates, for example:
       [(0, 11), (0, 10), (0, 9), ..., (0, 0), (1, 11), (1, 10), ..., (11, 1), (11, 0)]
    """

    # Get the size of the game board from JSON
    map_field_height = data['layers'][0]['height']
    map_field_width = data['layers'][0]['width']

    # Create map - list of x, y tuples 
    # Transformation with reversed is required as the JSON tiles
    # are in the opposite y direction
    coordinates = []
    for y in reversed(range(map_field_height)):
        for x in range(map_field_width):       
            coordinates.append((x, y))

    return coordinates
```

Co se „štábní kultury“ týče, je dobré mít jeden řádek s krátkým (jednořádkovým!) popisem, pak řádek vynechat, a pak rozepsat detaily. Všechno v „trojitých dvojitých“ uvozovkách, `"""`.

**Comment by anezkamll** [comment]
@encukou Díky moc, upravím! 👍

**Comment by amazonkaarya** [comment]
mám ty komentáře rozdělané pro celý Karolinin kód, pokusím se co nejdřív to znovu předělat podle tohoto

**Comment by encukou** [comment]
Doporučuju je přidávat postupně, radši než všechny najednou. Ostatní pak vidí že se něco děje, je míň práce to aktualizovat když se kód změní, a dřív se přijde na případnou systematickou chybu.

**Comment by encukou** [comment]
Když se tak koukám do kódu, poznamenám:
Dokumentační řetězec musí být řetězec (tedy v uvozovkách; ne komentář s `#`) a musí být vevnitř ve funkci (hned na začátku).
Dokumentační řetězce sluší všem funkcím, i těm testovacím.
