### ISSUE TITLE
Interface vykreslí tolik robotů, kolik je spoluhráčů

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#280]
PR #279 naťukl další úpravičku: Dole v interface jsou okýnka s ostatními hráčí. Interface vykreslí tolik okýnek (i s roboty), kolik je hráčů.

**Comment by ivet1987** [comment]
To už je hotové, jen pošlu PR :-D

**Comment by ivet1987** [comment]
https://github.com/PyLadiesCZ/roboprojekt/pull/281

**Comment by ivet1987** [comment]
done :)
