### ISSUE TITLE
Pokud robot má víc než 4 zranění, zablokují se mu příslušné karty na ruce

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#284]

**Comment by ivet1987** [comment]
Mám dotaz když o tom přemýšlím. Pokud si hráč bude vybírat méně než 5 karet, v robot.program tedy bude potom None, ok to jde oddělat, ale jak se potom provede apply_all_effect? Není tam nastaveno že musí být vždy 5? Pořád se mi to plete, ale ten register je ta jedna pětina že? @befeleme  Bude potom stačit z té metody jen odstranit že registers=5?

**Comment by encukou** [comment]
Bude pořád hrát s pěti. Ta pátá zůstane z minulého kola, nebude si ji vybírat.

**Comment by befeleme** [comment]
Promin, prehledla jsem zde komentar. Blokovana karta zustava v ruce hrace dokud si neopravi zraneni.
Nam staci pro informaci cislo, 1 - jedna blokovana karta az 5 - vsechny blokovane karty, abychom byly schopne identifikovat "zamcene" pozice. Vzdy totiz zaciname blokovat od posledni karty. 
Az to budeme mit, potrebujeme osetrit, aby do balicku pouzitych karet se tyto karty nedostavaly (stavajici reseni je jen polovicni).
