### ISSUE TITLE
Odstranit "WIP" z API

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/roboprojekt#29]
Věcem které se používají v jiném kódu, jako názvy souborů a funkcí  (`from jmeno_souboru import jmeno_funkce`), počet argumentů funkce (`jmeno_funkce(1, 2, 3)`) se říká **API** (*application programming interface*). Když se API nějaké funkce změní (přejmenuju soubor, změním počet argumentů), kód který tu funkci používal přestane fungovat.

Poznámky o tom, že je něco nedodělané, by neměly být součástí API. Pak totiž vznikají věci jako:
```python
from backend_WIP import get_tiles, get_coordinates, get_data
```
… které bude potřeba všechny opravit, až se `backend` „dodělá“. (Kdy to bude? Žádný kód není úplně hotový a perfektní, jsou v něm jen nedodělky s větší nebo menší prioritou.)

Poznámky "WIP" stačí mít mít v komentářích, dokumentaci, nebo *issues*.

**Comment by anezkamll** [comment]
Odstraněno z názvu souboru backend.py
