### ISSUE TITLE
Přidat porovnání, které herní kolo hrajeme

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#296]
Server posílá hrané kolo, robot si ho ukládá. Robot odesílá zprávu s kartami vč. herního kola, které obdržel s kartami, ale zde se zatím nic neděje. Potřebujeme zajistit, že se hodnoty porovnají a v případě, že se shodují, hra pokračuje. Pokud se neshodují, server nebere karty v potaz a z odeslaných tomu hráči karet mu přiřadí náhodné v místa None.

**Comment by ivet1987** [comment]
tak abych pravdu řekla, vůbec nechápu, co tím myslíš. Kdy ta situaci nastane?
Server pošle klientovi číslo kola a ten si ho uloží. Hráči vyberou karty, provedou se efekty a navýší se číslo kola, poštou se znovu karty s číslem kola, takže zase všichni mají stejné číslo.

**Comment by befeleme** [comment]
Ano, ale muze se stat, ze klient posle sve karty pote, co server uz "uzavrel" vyber. Nyni tato situace nenastane, ale s casovacem ano. V okamziku, kdyz cas vyprsi, navysi se herni kolo a pripadne zpravy se starym cislem nebudou brany v potaz (=server vybere hraci zbytek karet a hrac nebude schopen si tyto karty a) prepsat, b) pouzit pro dalsi kolo a podvrhnout tak vyber karet, ktere mu da server.

**Comment by ivet1987** [comment]
Právě nad tím časovačem teď sedím, zatím na straně serveru. Když poslední robot nemá vybrané karty, tak se spustí časovač a potom tam mám znovu podmínku že zkontroluje pokud má vybráno. Jestli ano, fajn, jestli ne, přiřadí mu ty karty. Jen teď právě nevím, jak se to zobrazí nebo nezobrazí na tom clientovi. Normálně se pak provede herní kolo, pošle se nový stav, ze kterého si načte to kolo. A teď to musí se právě nějak dořešit na straně klienta, to zatím nevím jak bude, nějak mu to potom znemožnit dál vybírat.

**Comment by ivet1987** [comment]
Diskuze v úterý 
Myslím že toto již není aktuální a nemůže nastat, nebo ano? Možná jsem časovač napsala jinak než se předpokládalo :-) 
Nyní pokud uplyne časovač, tak se klientovi vykreslí nové karty a nemůže tedy jak poslat staré. Nebo jo?

**Comment by encukou** [comment]
> Nyní pokud uplyne časovač, tak se klientovi vykreslí nové karty a nemůže tedy jak poslat staré. Nebo jo?

Komunikace mezi programy není okamžitá. Zpráva o nových kartách se klidně může zdržet. Až se klienti budou pouštět na jiném počítači, může se zdržet třeba i pár vteřin – a mezi tím by klient mohl poslat instrukce pro minulé kolo.
