### ISSUE TITLE
Chybí obrázky políček

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/roboprojekt#3]
* [x] zeď
* [x] vlajka (1-8)
* [x] startovací políčka (1-8)
* [x] laser (začátek, paprsek)
  * [x] jednoduchý
  * [x] dvojitý
  * [x] trojitý
* [x] posuvníky *(pushers)* (1/3/5 a 2/4)
* [x] díra
* [x] zem
* [x] pohyblivý pás
  * [x] 1 rovný
  * [x] 1 křižovatka
  * [x] 1 zatáčka (doprava, doleva)
  * [x] 2 rovný
  * [x] 2 křižovatka
  * [x] 2 zatáčka (doprava, doleva)
* [x] Otáčecí kolečko (doprava, doleva)
* [x] Opravovací políčko
  * [x] Vylepšovací políčko

**Comment by vahalova** [comment]
Prosím tě, co je posuvníky a ty divný čísla?

**Comment by vahalova** [comment]
A pás má i křižovatky. Dopíšeš to tam prosím?

**Comment by JureckovaK** [comment]
Beru si startovací políčka

**Comment by hroncok** [comment]
@vahalova Taky mi padá Inkscape, když píšu text. Už s tím bojuju dost dlouho a [nejsem sám](https://bugzilla.redhat.com/show_bug.cgi?id=1578924).

Verze z flatpaku by prý padat neměla, tak to zkouším a dám vědět, jestli to pomohlo.

https://fedoramagazine.org/getting-started-flatpak/

https://flathub.org/apps/details/org.inkscape.Inkscape

```console
$ sudo dnf remove inkscape
$ sudo dnf install flatpak
$ flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
$ flatpak install flathub org.inkscape.Inkscape
```

(Bacha, je to poměrně velké.)

(Nevím, jak ten Inkscape pustit, to je zas vynález.)

**Comment by vahalova** [comment]
Dík! 
Rychlotest padání prošel. @anezkamll to tě bude taky zajímat.
