### ISSUE TITLE
Nakreslit hratelne mapy :-)

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#309]
Uz je cas!

**Comment by ivet1987** [comment]
Máme někde napsaný postup pro tvoření map? Jako co má být v které vrstvě, otočení políček jestli se nějak musí hlídat atd...

**Comment by ivet1987** [comment]
Budeme ještě kreslit nějaké mapy nebo zavíráme? :-D @befeleme

**Comment by befeleme** [comment]
Ja bych rekla, ze nam ty prave hratelne mapy furt chybi. A zaslouzi si lepsi setrideni ve strukture projektu.

**Comment by ivet1987** [comment]
@befeleme pro kolik hráčů mám kreslit? :-D

**Comment by encukou** [comment]
Ideálně pro 8, kdyby se udělalo https://github.com/PyLadiesCZ/roboprojekt/issues/406

**Comment by ivet1987** [comment]
pár jsem nakreslila :) https://github.com/PyLadiesCZ/roboprojekt/pull/407

**Comment by ivet1987** [comment]
úklid a upravení map na hratelné https://github.com/PyLadiesCZ/roboprojekt/pull/430

**Comment by ivet1987** [comment]
new maps https://github.com/PyLadiesCZ/roboprojekt/pull/437
