### ISSUE TITLE
Po každém herním kole vytvořit nový čerstvý stav interface, stávající zahodit

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#332]
Máme v interface spoustu přepínačů, a atributů, které nyní po každém kole čistíme. Petrův návrh: po každém provedeném kole vytvořit nový stav, v něm nastavit jen to, co nám pošle server. Ze stávajícíh údajů chceme přenést do nového stavu:
- robota
- blokované karty na ruce

Něco ještě?

**Comment by ivet1987** [comment]
jak se vytvoří nový interface? Po určitém kroku se napíše `self.state = InterfaceState()`?

**Comment by befeleme** [comment]
Ano. Nebo se to zabali do nejake hezke funkce, ktera vyzobe ze stareho stavu atributy, ktere chceme ponechat, a priradi je rovnou novemu stavu.
Napr:
```python
def set_new_state(self):
    my_robot = self.state.robot
    new_state = InterfaceState()
    new_state.robot = my_robot
    return new_state
```

**Comment by encukou** [comment]
Doporucuju si robota i blokovane karty znovu poslat ze serveru, a z predchoziho stavu neprenaset nic.
 Melo by to byt jednodussi, a do budoucna to mozna dost zjednodusi kod kolem toho, ze se klient z nejakeho duvodu odpoji a chce se znovu pripojit.

On August 7, 2019 9:05:58 PM GMT+02:00, Karolina <notifications@github.com> wrote:
>Máme v interface spoustu přepínačů, a atributů, které nyní po každém
>kole čistíme. Petrův návrh: po každém provedeném kole vytvořit nový
>stav, v něm nastavit jen to, co nám pošle server. Ze stávajícíh údajů
>chceme přenést do nového stavu:>
>- robota>
>- blokované karty na ruce>
>>
>Něco ještě?>
>>
>-- >
>You are receiving this because you are subscribed to this thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/PyLadiesCZ/roboprojekt/issues/332

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ivet1987** [comment]
https://github.com/PyLadiesCZ/roboprojekt/pull/335
