### ISSUE TITLE
Jednotne formatovani kodu v souborech

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#334]
Nezavedeme kontrolu blackem? 
https://pypi.org/project/black/

Pak budeme mit ty soubory kazda stejne a prestaneme si pridavat/ ubirat mezery tu a tam.

**Comment by ivet1987** [comment]
Dobrý nápad, můžeme probrat a zprovoznit na příštím srazu.

**Comment by befeleme** [comment]
Vsichni povinne precist PEP8 https://www.python.org/dev/peps/pep-0008/

**Comment by befeleme** [comment]
Tak to uz asi muzeme zavrit pro nezajem verejnosti ;).
