### ISSUE TITLE
"sloty" na vlajky na klientovi by se mohly vykreslit podle poctu vlajek ve hre

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#346]
aby hraci hned videli, kolik vlajek musi posbirat, aby hru uspesne ukoncili.

**Comment by ivet1987** [comment]
jéé hezký úkol :)

**Comment by ivet1987** [comment]
https://github.com/PyLadiesCZ/roboprojekt/pull/347

**Comment by encukou** [comment]
Všiml jsem si že se tu občas objeví takovéhle komentáře bez kontextu. Bylo by fajn vždycky říct co to číslo je, třeba:

> Opraveno v #347
