### ISSUE TITLE
mame bug - roboti nejdou podle zvolenych karet :( 

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#348]

**Comment by ivet1987** [comment]
jakto? :-o já mám zase pocit, že je problém, když robot jde přes vlajku, tak ji nesebere, že musí zastavit přesně na ní.

**Comment by befeleme** [comment]
Podle vseho si vyberou karty, a na konec i tak dostanou randomove.

bender [
0: <right 210 Rotation.RIGHT>, 
1: <right 260 Rotation.RIGHT>, 
2: <back_up 255 -1>, 
3: <move2 445 2>, 
4: <move3 515 3>, 
5: <move2 440 2>, 
6: <right 270 Rotation.RIGHT>, 
**7: <move1 330 1>,** 
8: <move2 420 2>]

Vyber: [7, 0, 3, 5, 8]


bishop [
0: <right 230 Rotation.RIGHT>, 
1: <left 155 Rotation.LEFT>,
2: <right 205 Rotation.RIGHT>,
3: <move2 425 2>, 
4: <left 120 Rotation.LEFT>, 
5: <move1 375 1>, 
6: <right 220 Rotation.RIGHT>, 
**7: <move1 320 1>,** 
8: <u_turn 75 Rotation.U_TURN>]

Vyber: [7, 2, 3, 5, 6]


playing bender <move2 420 2> 
playing bishop <right 220 Rotation.RIGHT>

playing bishop <move1 375 1>
playing bender <right 260 Rotation.RIGHT>

playing bender <move1 330 1>
playing bishop <left 155 Rotation.LEFT>

playing bender <move2 445 2>
playing bishop <left 120 Rotation.LEFT>

playing bishop <right 230 Rotation.RIGHT>
playing bender <right 210 Rotation.RIGHT>

**Comment by ivet1987** [comment]
@encukou myslíš že je problém v metodě `robot.select_cards`? Přijde mi napsaná správně :-\

**Comment by ivet1987** [comment]
@befeleme a kontrolovala jsi rozdané karty jestli se vykreslují správně prosím?

**Comment by ivet1987** [comment]
> Ja myslim, ze jsme uz schopne to dohledat samostatne ;).
> Karty jsem kontrolovala, zde neni problem. Vsak si hru zahraj a vyprintuj par udaju, sama uvidis. Hledam to, ale mam jeste jen par minut, tak se radsi neupisuju k te issue. :/

jo tak během týdne budu mít čas to vyřešit, teď dělám něco jiného, ale přihodím si printy různě a zkusím najít chybu kde přesně :)

**Comment by befeleme** [comment]
Ok, kdo prvni, vyhrava! ;) Pokusim se jeste vecer to nejak prokouknout.

**Comment by befeleme** [comment]
> já mám zase pocit, že je problém, když robot jde přes vlajku, tak ji nesebere, že musí zastavit přesně na ní.

Myslis pripad, kdyz robot ma k vlajce 1 krok, ale v ruce drzi kartu na 3 kroky, a tak nad vlajkou "prejde"? Co rikaji o teto situaci pravidla?

**Comment by ivet1987** [comment]
> > já mám zase pocit, že je problém, když robot jde přes vlajku, tak ji nesebere, že musí zastavit přesně na ní.
> 
> Myslis pripad, kdyz robot ma k vlajce 1 krok, ale v ruce drzi kartu na 3 kroky, a tak nad vlajkou "prejde"? Co rikaji o teto situaci pravidla?

jojo tuhle situaci myslím, musím mrknout na pravidla, teď nevím :-D
