### ISSUE TITLE
Zbavit klienty herni logiky

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#364]
Na zaklade spolecne review: odtencit klienty, aby obsahovali co nejmene herni logiky, logiku prenest podle vyznamu do interface nebo interface_frontendu. 
Klient se ma primarne starat o udrzeni spojeni a reagovat na zpravy od serveru volanim prislusnych prvku ostatnich modulu.

**Comment by ivet1987** [comment]
solving https://github.com/PyLadiesCZ/roboprojekt/pull/368

**Comment by ivet1987** [comment]
@befeleme můžeme zavřít?

**Comment by befeleme** [comment]
Pokud je uz vsechno, co jsi planovala, zacleneno, proc ne.

**Comment by ivet1987** [comment]
Ok, vic určitě ne, treba bude jeste pozdeji zase něco treba, ale hotovo :)
