### ISSUE TITLE
Opravit oživení robota - stojí na špatné vlajce

### ISSUE THREAD

**Issue by ivet1987** [PyLadiesCZ/roboprojekt#366]
Když robot umřel, narodil se na jakékoli poslední vlajce, na které stál, ne tu kterou naposledy získal.

**Comment by befeleme** [comment]
Koukala jsem do pravidel v obou jazycich a mam z toho takovy divny pocit - da se to vylozit dvojim zpusobem... Tak to zmenime, nebo nechame, jak ted je?

> Každý robot, který přežil boj až do tohoto bodu a stojí na vlajce, "získá" vlajku. Počínaje další fází Registrů se může přesunovat k následující vlajce podle pořadí (může být užitečné používat papír a tužku k zaznamenávání vlajek, které již hráči "získali").
> **Každý robot, stojící na vlajce nebo na stanovišti opravy, aktualizuje svou virtuální lokaci** položením své Virtuální značky na toto pole. Jestliže je robot zničen před dosažením další možné virtuální lokace, tak je tato dosavadní lokace místem pro jeho Reenter hry.

**Comment by ivet1987** [comment]
Tý jo, tak nevím, teoreticky to můžeme nechat, může to být vlastně část strategie robota, že si vleze na jinou vlajku aby se tam znovu narodil v případě smrti.
