### ISSUE TITLE
Vykreslit Power Down na robotovi

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#373]
Mam prosbu: nekamaradim s inkscape. 
Uz jsem skoro hotova s power down, ale chybi vykresleni power down na malem avataru hrace. 
Klidne ten stehny obrazek, mensi, pres hracuv avatar, neco jako "stopka".
Atributy pro to mame uz i v masteru, tak by nemel byt problem vykreslit PD pokazde, kdyz je zmacknuta klavesa P. 
Prosbu mirim na @ivet1987 
Smutne koukam ;)

**Comment by ivet1987** [comment]
Jasně to udělám, to mě baví :-D
