### ISSUE TITLE
Nevykresluji se korunky pote, coz nekdo vyhraje hru

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#376]
Odtenceni klienta zpusobilo, ze hra korektne vyhodnoti viteze, ale nevykresli mu korunku, stejne tak nevykresli korunky na avaterech.
Zavedeno nejspis v #368

**Comment by ivet1987** [comment]
Mrknu, zjistím, opravím :)

**Comment by ivet1987** [comment]
solved in https://github.com/PyLadiesCZ/roboprojekt/pull/380
