### ISSUE TITLE
Hra spadne protoze interface nezna sveho robota

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#377]
Pokousime se tady s Pavlikem hrat po siti. 
Hra nam uz potreti spada se stejnou chybou na strane interface u jednoho hrace: 

```
Traceback (most recent call last):
  ...
  File "client_interface.py", line 31, in window_draw
    draw_interface(self.interface_state, self.game_state, self.window)
  File "roboprojekt/interface_frontend.py", line 223, in draw_interface
    if interface_state.robot.name not in robot.name:
AttributeError: 'NoneType' object has no attribute 'name'
```

Bohuzel nevime, co presne chybu zpusobuje. Nejakou dobu v klidu hrajeme (10-15 minut), a pak mame fail. Vypada to, ze v interface se muze stat, ze ho chceme vykreslit, aniz by mel prirazeneho robota.

**Comment by ivet1987** [comment]
Předpokládám že by to mělo vyřešit přidání podmínky do interface_frontend.py řádek 285
if interface_state.robot upravit na `if interface_state.robot is not None` zkuste.

**Comment by ivet1987** [comment]
Jo to je jiný řádek, tak tam i nad ten  223 pokud to není None

**Comment by befeleme** [comment]
Pokud tam das `if interface_state.robot is not None`, vykresli se ti vsichni hraci dole vcetne sebe sama. ale je pravda, ze pak uz nam to na teto chybe nespadlo.

**Comment by ivet1987** [comment]
> Pokud tam das `if interface_state.robot is not None`, vykresli se ti vsichni hraci dole vcetne sebe sama. ale je pravda, ze pak uz nam to na teto chybe nespadlo.

Ok díky, tak to zkusím promyslet.
