### ISSUE TITLE
Vypsani viteze nepocita s mapou jine velikosti nez 12 policek

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#378]
A to se nam stalo u hry na delsi mape :-)
Napis je nad modrym robotem.

![winner](https://user-images.githubusercontent.com/33810531/65392579-9a881600-dd76-11e9-8ee0-169ec29f74e4.png)

**Comment by ivet1987** [comment]
Ano protože jsem myslela, že necháme mapy max 12 políček, nějak opravím :-)
