### ISSUE TITLE
Robot skonci mimo hraci plochu, ale klient si toho nevsimne

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#379]
Pokud se robot dostane mimo hraci plochu, obcas si toho interface tak nejak nevsimne. Robot se nevrati na startovni policko, ale karty se mu vymeni a muze si vybrat z novych karet. Umre teprve po zahrani tech novych karet a vrati se na start. Zda se nam, ze tento stav je vyvolan, pokud hrac vypadne z hry posunem pasu.

![out-of-game](https://user-images.githubusercontent.com/33810531/65392893-56971000-dd7a-11e9-92d2-34d6bbe10716.png)
![smrt](https://user-images.githubusercontent.com/33810531/65392894-5a2a9700-dd7a-11e9-82be-b0351edb6971.png)

**Comment by ivet1987** [comment]
fixed in https://github.com/PyLadiesCZ/roboprojekt/pull/394
