### ISSUE TITLE
Vyresit odpojeni klientu

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#384]
Klienti, kteri se z hry odpoji: 
- odstrani se ze slovniku assigned_robots
Jejich robot:
- se prenese do seznamu available_robots
- se nebude mazat ze seznamu robotu
- nastavi se pokazde na Power Down
Nebude se resit potvrzeni vyberu karet u techto robotu pro timer - nechceme pokazde cekat 30 vterin.
Pokud se klient opet pripoji, dostane prvniho volneho robota z seznamu a muze hrat dal.

**Comment by ivet1987** [comment]
Zapomněla jsem jak to bude fungovat, proč že se nebude mazat ze seznamu robotů? Bude tedy dál vykreslen na obrazovce? To je jako případ že to přestane někoho bavit a jen to zavře? A když se někdo připojí - ten stejný nebo někdo jiný? - dostane robota ve stavu v jakém se odpojil původní hráč jo?

**Comment by befeleme** [comment]
> Zapomněla jsem jak to bude fungovat, proč že se nebude mazat ze seznamu robotů? Bude tedy dál vykreslen na obrazovce? To je jako případ že to přestane někoho bavit a jen to zavře? A když se někdo připojí - ten stejný nebo někdo jiný? - dostane robota ve stavu v jakém se odpojil původní hráč jo?

Na srazu jsme se domluvili, ze udelame ty roboty vzdy power down a budou na plose za nekativni prvky, dokud se nekdo nepripoji a nevezme je na sebe.

**Comment by encukou** [comment]
Není to jen případ že to někoho přestane bavit a zavře okno, ale i případ kdy vypadne spojení nebo spadne systém. Jestli to má být hratelné po internetu, je potřeba s takovýma věcma počítat.
