### ISSUE TITLE
Roboti stojí na sobě

### ISSUE THREAD

**Issue by ivet1987** [PyLadiesCZ/roboprojekt#388]
Vůbec nevím co to zase je :-D
Modrý stál na souřadnicích (3,2) a žlutý evidentně mezitím umřel. Tak nevím jestli měli zůstat stát, když šli spolu na stejné poličko, nebo se spíš posunout, přesné karty už nevím. V dalším tahu už se normálně posunuli.
![Snímek z 2019-09-29 10-47-26](https://user-images.githubusercontent.com/39279854/65829620-9775b400-e2a7-11e9-9cb0-5eecf19abf3e.png)

**Comment by ivet1987** [comment]
předpokládám že se vyřeší a je to chyba tohoto https://github.com/PyLadiesCZ/roboprojekt/issues/235

**Comment by befeleme** [comment]
Nojo, neni to chyba, tak to zatim mame napsane. Je to k vyreseni.

**Comment by encukou** [comment]
Bohužel to stále může nastat :(
Dva roboti sice nemůžou mít stejné `start_coordinates`, ale když se robot znovu objeví na mapě, na jeho `start_coordinates` může zrovna jiný robot být.

**Comment by befeleme** [comment]
:(
Můžeme zkontrolovat při reinicializaci, že políčko není obsazeno jiným robotem. 
V případě, že je, zkontrolují se políčka sousedící, a pokud jsou to "podlahy" a zároveň na nich nikdo nestojí, vybralo by se náhodně jedno z nich. 
Pak ale taky může nastat situace, že kolem startovního políčka bude tolik významotvorných prvků v kombinaci s neobvyklým soustředěním robotů, že výběr se nepovede. 
Máte nápad, jak to vyřešit lépe?

**Comment by encukou** [comment]
Napadlo mě ještě jedno možné řešení:
- Robot se objeví na posledním prázdném "ukládacím" políčku, na kterém byl
- Na startovací políčko se nedá vjet (robot z něj může jen odjet, když se na něm objeví)

**Comment by ivet1987** [comment]
Nerozumím - na startovací políčko se nedá vjet? Jako ten konkrétní robot nebo všichni roboti?

**Comment by encukou** [comment]
Myslel jsem všichni roboti, aby vždycky bylo aspoň jedno prázdné políčko, kde se robot může objevit.

**Comment by befeleme** [comment]
Nejsem si jistá, že rozumím: 
- každý robot si uschová seznam svých startovacích políček v pořádí, jak na ně šlape.
- pokud poslední políčko v seznamu je obsazeno, podívá se na předchozí políčko. 
    - pokud není obsazeno - reinicializuje se tam
    - pokud je obsazeno, podívá se na předpředposlední atd. 
- kdyby nic z toho nevyšlo, není problém, protože první záznam jsou vždy jeho původní startovací koordináty, které si nikdo nemůže přivlastnit.

Takže přestát zamezovat změnu, místo toho přidávat možnosti do nějakého pytle?

**Comment by ivet1987** [comment]
To jde nějak mimo mě. Jako startovací políčka jsou přece vlajky a na ty se musí dát vjet. Nebo co je to poslední prázdné ukládací políčko?

**Comment by encukou** [comment]
„Ukládacím políčkem“ myslím políčko, které nastaví `start_coordinates`: aktuálně `repair` a `flag`.

**Comment by befeleme** [comment]
Doplním: startovací políčka jsou ty se startem-číslem. Ty si nikdo nemůže vzít, prostě na nich na začátku je, přitom každá má zaručené jiné koordináty. 
Tento nápad se mi líbí, zapracuji na tom.

**Comment by befeleme** [comment]
Ha. Pokud robotovi dojdou vsechny moznosti, kde se reinicializovat (napr. jeste neziskal zadnou vlajku), ale na jeho startovacim policku zrovna kempuje nekdo jiny, pak se nevrati do hry vubec. V takovem pripade napada me umoznit robotovi reinicializaci na dalsim startovacim policku, ktere najde, a ktere bude volne.
