### ISSUE TITLE
Po zmenach interface roboti "vychazi" ze svych mist

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#398]
![image](https://user-images.githubusercontent.com/33810531/66987904-e1d99c00-f0c1-11e9-89c0-38a63d100aa5.png)

U map s vicero hraci uz to nevypada dobre.

**Comment by ivet1987** [comment]
solved in https://github.com/PyLadiesCZ/roboprojekt/pull/399
