### ISSUE TITLE
Obrázky robotů 

### ISSUE THREAD

**Issue by vahalova** [PyLadiesCZ/roboprojekt#40]
- [x] Terka
- [x] Karolina
- [x] Anežka
- [x] Hanka
- [ ] Zuzka
- [x] Katka
- [x] Iveta
- [x] Helena

**Comment by vahalova** [comment]
Na roboty mě napadají 3 způsoby:
1) Na robota se díváme shora - má předek, kde střílí a otáčí se dokola obrázek
2) Na robota se díváme zepředu - střílí jedním určeným směrem (hlava, ruka(?)) a otáčí se dokola obrázek
3) Robot má 4 obrázky - přední, zadní a 2 boky a dosazuje se obrázek podle toho kam se zrovna dívá. Přední - robot jde dolů, zadní - jde nahoru..
Než začnete, tak se pojďte dohodnout, ať to nekreslíme každá jinak.

**Comment by encukou** [comment]
Muzete zacit i bez domluvy. Kdyz budete mit par konkretnich navrhu (kazdy
muze zabrat jen 5 min, muze to byt treba jen nakreslene na papire), bude se
vam domlouvat mnohem lip.

**Comment by vahalova** [comment]
Řešíme na Slacku.
Aktuální návrh:
malý barevný 'čtvereček', co má směr - jako robot na mapě, pohled shora
velký detailnější robot zepředu - jako ikona hráče - použití třeba pro 'kdo je na tahu'
