### ISSUE TITLE
V serveru nastavit počet hráčů

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/roboprojekt#406]
V původní deskovce jsou všechny mapy pro 8 hráčů. Když je hráčů míň, některá startovací políčka se nepoužijí.

Při zapínání serveru by se mohl dát vybrat počet hráčů, s tím že se při načítání mapy budou ignorovat startovací políčka s vyšším číslem.

**Comment by ivet1987** [comment]
:-) pár jsem nakreslila  https://github.com/PyLadiesCZ/roboprojekt/pull/407

**Comment by ivet1987** [comment]
Není mi jasné jak to má fungovat, respektive to ignorování startovacích políček. Jako vytvoří se nebo se ani nevytvoří? Respektive budou zobrazené ale nebude se s nima pracovat že? Hezký úkol, ale nevím jestli na něj budu mít čas :(

**Comment by encukou** [comment]
Všechny možnosti, které vyjmenováváš, by se daly použít. První úkol je navrhnout řešení.

(Jestli chceš znát můj názor, tak ten je že by se do rozehrané hry mohl kdykoli připojit nový klient, až do limitu mapy. Nový klient by dostal nového robota a začal by s 0 vlajkama na dalším zatím nepoužitém startu. Ale to je ještě složitější.)

**Comment by ivet1987** [comment]
Vždycky chci znát tvůj názor. 😁 Promyslím a jestli budu mít čas tak se pokusím. 
Každopádně jestli se na to chce někdo vrhnout, směle do toho, já do konce týdne čas nemám  😔
