### ISSUE TITLE
Uklidit složku maps/ + překreslit hrací políčka

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#409]

**Comment by encukou** [comment]
Předpokládám že tohle znamená:
- [ ] v maps nechat jen hratelné mapy, ostatní přesunout třeba do podadresáře
- [ ] hratelné mapy hezky/originálně pojmenovat
- [ ] pro hru (ne Tiled) nakreslit políčka, která např. nemají šipky u laserů

**Comment by befeleme** [comment]
Varianta nice-to-have:

- [ ] u nekterych robotu neni zhora videt, kam smeruji, bylo by dobre jim dat hezkou zaoblenou sipecku
- [ ] policka by mohly vic barevne ladit, not so vintage
- [ ] welcome board by mohl barevne ladit s interfacem
