### ISSUE TITLE
Pokud nekdo vyhral, vyhlaseni viteze se odehrava po kazdem kole.

### ISSUE THREAD

**Issue by befeleme** [PyLadiesCZ/roboprojekt#413]
Asi bug. Pokud uz nekdo vyhral, tabule s vitezem uz by nemusela se vykreslovat po kazdem dalsim zahranem kole.

**Comment by ivet1987** [comment]
Kde se co rozbilo?  Vždyť to fungovalo. 😂 Mrknu na to během zítřka. 😁

**Comment by ivet1987** [comment]
Bohužel to spíše nevidím, kdo by měl čas, může mrknout, nebo vyřešíme v úterý.

**Comment by befeleme** [comment]
Nevím, kdy se to stalo, ale před začleněním #405 jsem schválně koukala na master a už se tam toto dělo. Takže to bude nějaká dřívější změna, kterou nemůžu vysledovat.

**Comment by ivet1987** [comment]
Nevím jestli je to správné řešení, každopádně vypadá že funguje, snad to bude ok :)
