### ISSUE TITLE
client_interface: Ukázat dole všechny roboty, včetně hráčova

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/roboprojekt#415]
Přijde mi trochu nepřehledné, že počet vlaječek/životů/zranění se pro mého robota ukazuje jinak než pro všechny ostatní. Blbě se porovnává, jak na tom kdo je.
Šlo by dát dolů informace o všech robotech, a případně nějak „vysvítit“ toho hráčova?

**Comment by ivet1987** [comment]
Nevím, mě se líbí jak to je :-D Pro mě by to bylo zase nepřehledné, kdyby dole strašil ještě můj další robot :-D Asi o zvyku a věc názoru. Případně ten můj robot aby byl první vysvícený a ne někde uprostřed zvýrazněný.

**Comment by ivet1987** [comment]
A nestačilo by ti to zobrazení vlastností dát do rámečku vlevo nahoře jak je obrázek tvého robota aby to vypadlo stejně jako u ostatních hráčů?

**Comment by encukou** [comment]
Možná by to fungovalo, ale asi bych si to s tím musel zahrát, než odpovím :)
Ale celé to je detail, klidně tuhle issue zavřete.

**Comment by befeleme** [comment]
Přijde mi to jako dobrý nápad. Rámeček vlastního robota by mohl být trochu tmavší, aby bylo jasné, že to není soupeř. A měl by se vždy zobrazit jako první. Jsem pro to to tam dát.

**Comment by ivet1987** [comment]
A chcete rozšířít jako celou obrazovku nebo zúžit obrázky ostatních robotu, aby se tam vlezli všichni?

**Comment by befeleme** [comment]
hm, kdyby jim ubrat vzdalenosti mezi sebou a od kraje, mozna by se v pohode vesel?

**Comment by ivet1987** [comment]
vyřešeno https://github.com/PyLadiesCZ/roboprojekt/pull/438
