### ISSUE TITLE
Když chci umístit kartu na zablokované místo, tak interface "spadne"

### ISSUE THREAD

**Issue by vahalova** [PyLadiesCZ/roboprojekt#417]
File "/home/terezievahalova/dev/roboprojekt/interface.py", line 46, in select_card
self.program[self.cursor_index] = dealt_card_index
IndexError: list assignment index out of range

**Comment by ivet1987** [comment]
Nechápu jak se ti to povedlo, jak jako umístit kartu na zablokované místo? Vždyť to nejde, ten kurzor se na zablokovanou pozici nedostane, můžeš popsat víc tu situaci?

**Comment by vahalova** [comment]
Klikneš na zablokovanou kartu, tím se ti tam dostane kurzor a klikneš na kartu, co tam chceš přiřadit.

**Comment by ivet1987** [comment]
Ajo, už mi to taky padá, předtím jsem to zkoušela a nešlo mi to, nevím, mrknu, díky za chybu.
