### ISSUE TITLE
Jak vyřešit zeď?

### ISSUE THREAD

**Issue by anezkamll** [PyLadiesCZ/roboprojekt#45]
Z UML diagramů zůstalo nedořešené téma, jak bude definovaná zeď v rámci efektu políčka.
Otevírám tedy tímto téma k zamyšlení a diskusi. 
Souvisí s #22.

**Comment by encukou** [comment]
Až vyřešíte #22 a #19 a jeden další úkol co na nic závisí, napíšu k tomu něco víc :)

**Comment by encukou** [comment]
Ten další úkol je #81

**Comment by encukou** [comment]
Na srazu padla zajímavá myšlenka: Robot se při pohybu „zeptá“ aktuálního políčka, jestli může daným směrem odejít, a nového políčka, jestli na něj může daným směrem přijít. Každé políčko tak potřebuje informace jen o „svých“ zdích, a zeď může být jen u jednoho z nich.

**Comment by befeleme** [comment]
Ještě trochu o zdech... Jedna věc je načítání, další - estetické řešení mapy. Momentálně si zeď můžeme naplacat v jakémkoli směru, dokonce obkličit políčko (ve 4 vrstvách mapy). Můžeme postavit zeď na sever políčka a u sousedícího s ní - na jih - udělat ji tak dvojitou. Můžeme sousedící políčka oddělit z libovolné strany a budí to ve mně vnitřní neklid - příklad uprostřed dole, kde jsou dvá způsoby na L-tvar. Nebylo by lepší se dohodnout třeba na pravidle: vykreslení zdi ve směru jih v jedné vrstvě, ve směru západ ve druhé vrstvě, čímž důsledně můžeme pokrýt celou hru? Možná řeším neexistující problém, tak se mi to nebojte vyvrátit. :) 

![walls](https://user-images.githubusercontent.com/33810531/49688923-affabf00-fb19-11e8-9b60-cbf7f6692289.png)

**Comment by encukou** [comment]
K tomuhle návrhu bych asi chtěl říct víc než stihnu do úterka napsat. Diskutujte, ale doporučuju zatím nedělat změny v mapách/kódu – do útrerka se radši držte původního plánu.

**Comment by encukou** [comment]
Tohle je už v cajku, grafiku ošéfujete pak.
