### ISSUE TITLE
Dopsat README

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/roboprojekt#50]
Soubor README.md je vizitka projektu; GitHub ho ukazuje na hlavní stránce. Měly by tam být věci jako:
* co ten program dělá
* jak to nainstalovat (většinou předpokládám že čtenář má aktivované virt. prostředí, ale ten předpoklad tam zmíním), 
* jak to spustit
* jak spustit testy
* jak se zapojit (zatím asi nechcete aby se do toho zapojovali cizí lidi)

**Comment by anezkamll** [comment]
@encukou Má smysl udělat teď aspoň nějaké provizorní, ať to má aspoň základní informační hodnotu (zatím jen co je to za repozitář, co má za účel a odkaz na blog)? Jestli jo, tak to udělám.

**Comment by encukou** [comment]
Má. Až se mě někdo zeptá jak se tu spouští testy, rád bych ho měl kam odkázat :)

Každý proces, včetně instalace, je dobré popsat. Často tak najdeš chybky, nepříjemnosti nebo nápady jak ten proces zjednodušit.

**Comment by befeleme** [comment]
- Aktualizovat info o spusteni hy (server client rozhrani)

**Comment by befeleme** [comment]
- Po zmenach ve validatoru stabilizovat poradi vrstev policek na mapach a aktualizovat readme podle finalniho stavu

**Comment by befeleme** [comment]
Pridat informaci, jak propojit klienty a server, resp. napsat jednoduche propojovatko, aby uzivatel nemusel menit vselico po souborech :-)
