### ISSUE TITLE
Použít třídu na efekt políčka 

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/roboprojekt#54]
„Obrázky“ políčka jsou aktuálně reprezentovány jako dvojice (ID políčka, rotace). Dvojice není úplně ideální: když z ní chci jednotlivé prvky, musím dělat buď:
* `value[0]` a `value[1]` (takže není poznat co dostávám), nebo
* `coordinate, rotation = value` (což je super do té doby, než budu potřebovat další kousek informace, a bude potřeba všechno předělat na trojice).

Použijte na to místo dvojice třídu.

**Comment by JureckovaK** [comment]
Zkusím se na to o víkendu podívat.
