### ISSUE TITLE
Odstranit Tile(0, 0)

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/roboprojekt#73]
Když je v JSON mapě prázdné políčko (`id=0`), je reprezentováno pomocí `Tile(path=0, rotation=0)`:

https://github.com/PyLadiesCZ/roboprojekt/blob/29125f35df507d88a10f46c1f0f499ba62561b23/backend.py#L58-L66

Ve frontendy je pak pro `path=0` speciální logika:

https://github.com/PyLadiesCZ/roboprojekt/blob/29125f35df507d88a10f46c1f0f499ba62561b23/frontend.py#L43-L47

Nebylo by lepší takovéhle „nepolíčko“ do seznamu `tilelist_layer` vůbec nedávat?

---

Na tomhle miniproblému nic dalšího nezávisí. Doporučuju někomu, kdo se v datovém modelu ještě úplně neorientuje (a má nějakou tu hodinku času). Jestli už teď víš jak to vyřešit, přenech to někomu jinému (nebo lépe, nabídni se jako kouč).

**Comment by vahalova** [comment]
Vyřešeno v #88
