### ISSUE TITLE
Dopsat `__repr__` do tříd

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/roboprojekt#80]

**Comment by ivet1987** [comment]
udělán PR

**Comment by encukou** [comment]
A ten PR je https://github.com/PyLadiesCZ/roboprojekt/pull/89.

(Je dobré na věci odkazovat, aby se každý kdo přijde mohl rychle zorientovat. Ten Pull Request časem zapadne a nebude snadné ho bez odkazu najít.)
(Do komentáře jsem zkopíroval celou adresu, `https://github.com/PyLadiesCZ/roboprojekt/pull/89`. GitHub to ukazuje zkráceně, jen jako https://github.com/PyLadiesCZ/roboprojekt/pull/89.)

**Comment by ivet1987** [comment]
https://github.com/PyLadiesCZ/roboprojekt/pull/91
