### ISSUE TITLE
Automaticky exportovat PNG obrázky

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/roboprojekt#85]

**Comment by vahalova** [comment]
Holky, kdo toto řeší? Koukám, že tu je @zstankova  a na Slacku to řeší @ivet1987

**Comment by zstankova** [comment]
Já se domlouvám s Ivet bokem, chtěla jsem ji s tím pomoct, ale po hodně hodinách snahy jsem nevymyslela nic kloudného, takže nic :( odstraním se od tud...

**Comment by anezkamll** [comment]
Domlouváte bokem? Skandál! :-D :-D

**Comment by ivet1987** [comment]
Jak kdo to řeší, však jsem označená :-D Zuzka mi jen chtěla pomoct tak psala, nic vám netajíme :-D

**Comment by ivet1987** [comment]
https://github.com/PyLadiesCZ/roboprojekt/pull/123
