### ISSUE TITLE
Větší mapy

### ISSUE THREAD

**Issue by vahalova** [PyLadiesCZ/roboprojekt#95]
Budeme potřebovat načítat větší mapy.
Aktuálně program neschroustá mapu rozšířenou o startovací pásek 12x4.

Vytvořit testovací mapu 12x16 a upravit kod, aby se zobrazovala celá.

**Comment by JureckovaK** [comment]
Já se už zase vrtám v kódu, tak to udělám.

**Comment by befeleme** [comment]
#103
