### ISSUE TITLE
Zařídit, aby se robot při pohybu zarazil o zeď

### ISSUE THREAD

**Issue by encukou** [PyLadiesCZ/roboprojekt#98]
Issues #84 (pohyb robota) a #82 (načítání efektů políček) vypadají že budou co nevidět vyřešené.
Myslím že je čas na první efekty políček!
Doporučuju se napřed zaměřit na zdi, než na ty ostatní.
Můžete přitom doladit, jak jsou efekty políček reprezentovány v kódu ­­– a zvášť jak reprezentujete zeď, #45.

**Comment by anezkamll** [comment]
Do třídy Tile načítat typ a vlastnosti políčka. Dané políčko pak bude mít metodu, jestli se z něj a na něj dá dostat.
